name: Test, Build and Deploy

# The workflow will run if the following conditions are met:
on:
  pull_request_target:
    types:
      - closed
    branches:
      - main

jobs:
  build:
    if: github.event.pull_request.merged == true
    name: Build
    runs-on: ubuntu-22.04
    steps:
      # Checkout the branch
      - name: Checkout branch
        uses: actions/checkout@v3

      # Set up Java/Maven.
      - name: Setting up Java / Maven
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      # Tests.
      - name: Tests
        run: |
          mvn test
      
      # Build.
      - name: Building jar
        run: |
          mvn clean package
